apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudfare-tunnel
  namespace: cloudfare
spec:
  chart:
    spec:
      chart: cloudfare-tunnel
      version: 0.3.x
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: cloudfare
  # values:
  releaseName: cloudfare-tunnel
  targetNamespace: cloudfare
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

