apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-snmp-exporter
  namespace: monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus-snmp-exporter
  interval: 10m
