apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      version: 0.15.x
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: metallb
  releaseName: metallb
  targetNamespace: metallb-system
  interval: 1h
