apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.18.x
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 1h
  values:
    crds:
      enabled: true
