apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  url: https://charts.jetstack.io # sadly the official oci repository does not seem to work...
