apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:m3/VadGaBd+mCopbKwJGPfbF8886H1bCQKfy3Z4TUN8gUtN1u2zr3Q==,iv:/tuFfZ+QLxHNv8yQhWxttJnpvPzgmmEtZPnUnpjKG24=,tag:BtyBDHAqAOAljKb42CCLWw==,type:str]
sops:
    age:
        - recipient: age1exre38frn2yaqqgjmdp39uqs2uc97r8p52nhhytt8g9tks0tdyvs37s7sq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQUUwUVlHWUlhLzVTcGla
            MzRFbFdRY0tMTzkralBnb2U1eEFLcFg3MlI0CldCTWJPcG0wd1JvcUVkNDI4WlR6
            WHlKakRYUE5Db2hIdC9sMGJaRm13NG8KLS0tIDRNdVFIMmUrM2tOOTFTVVhwZ2RO
            akcxTSttT2RVR3l4QkJLeXc3WFZmbmcKhC2n6iWwKlOnVu3mA1xlyEq0fvUN8DQ6
            3CX/kW3v32odWAcXS32i8o8z+YuR2FmW0slqp/UpJEQJnb9z29a3AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T16:31:33Z"
    mac: ENC[AES256_GCM,data:qJ6ioJjMc+GVp+LRH8N8lPjeBz/nAq/vB2AHazKmMrrLkEaQHflrGJwhtUZroGI+fY8bHhdeCK3+ATe4YyOSuIHvijH6reeJHB/ayNcBR6EAdFIGlv9TelSDwJfv2pcjNF3QhwJgcqXrEtsQQByz3dYFLdJHAIpR106nQMXJ4Ww=,iv:fa24hAZDe1QWu0n7T/+C9/LLPEYc0HpuPkZiUpYE4ng=,tag:YFhwGWcS70sfDBDOkmpc8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
