apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 0.3.x
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: cloudflare
  releaseName: cloudflare-tunnel
  targetNamespace: cloudflare
  interval: 1h
  values:
    cloudflare:
      tunnelName: "homelab"
      ingress:
        - hostname: '*.ndakkoune.com'
          service: http://nginx.nginx.svc.cluster.local:80
        - service: http_status:404
  valuesFrom:
    - kind: Secret
      name: cloudflare-secret
