apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel-remote
  namespace: cloudflare
spec:
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: 0.1.x
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: cloudflare
  releaseName: cloudflare-tunnel-remote
  targetNamespace: cloudflare
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: cloudflare-secret
