apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cloudflare
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:0Bnhzu0geQzxVuqTvW6gMbubQi1mIEYo086D/IUXzY2i77d5DXKbsX6r2jaqEtieF2ftB5QjkDXnhfWpEoyacdMoj5UkLUJeE4QxuNAXZGj/EPZHF/qVhER7n5Ghf9Fs5De1OjaLp0l+jj4qQC+3JicCMTBQQoe8CQjDgT6vaeQt9wY1UOAxyz99rqibmAvc2kcD7P05wG2TvZNQ0Pyr5VsuZL9/xYmrf6Ekc8GtPTcTY4CZ3aTIKQntEOeO3Mqmhlcn+KsMXVVIo0MfXOoeXfCp/ZmvqwM=,iv:yUXxndRzrVr0SinSQHCzepyJ4HM5Jx1Zp71IJuWD6Yc=,tag:p5N9oR7CXLlF+j/cEPcmKA==,type:str]
sops:
    age:
        - recipient: age1exre38frn2yaqqgjmdp39uqs2uc97r8p52nhhytt8g9tks0tdyvs37s7sq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMnRIOVBJMWZmckt3MnFx
            M3NUUTRrVWRqMjNGc2wrWjJ1MkJhaXJhN1dvCktjUVhXMTN0c3hMT1ZPa0RwMGNW
            K0VSU3A2YTVOdWlkYVphYWJCeFRRYncKLS0tIGEySzM0RFpVU0pNZHNZT3ltVHg3
            QVlsQ0F2RWtPQ0tSc0lyVWpoTjFLUUkKe1ptBIsGKiJeOuh3GhUuaZ+798mRklVd
            HMXFmbm+mi40wO2B8/i5tjIk4hKGpgVrXNMc6EqfAIuK99yjbkXdcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T13:32:04Z"
    mac: ENC[AES256_GCM,data:krJKAktEsr8/V5wQ+kyyJxxRVy8GX0k7lZmu64nIhGJin86gT40g9hP4B2rCaXIPcLyml4x/6prHK+GyMEOk2REed//ApxuzubKUkxcDC6vUZPlZKP9mCaeIGPAPCdlKNpNB1pAs54gg8mKm0VLFZYU6U7cfe2Hx+rAqJglR0uI=,iv:0ITw/jT975W3DynJfARvqWFEoqg/uYVy4e5gytHhOm0=,tag:YIuSeaNEsHyYxXlyesqEyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
