apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cloudflare
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:JWtx1fqBewOggagtxva6E3lt6W+Q+jznNey79NT+S6SBAQ88TPbIi6wkYEnFBF/qKXUa7BV4ABRWlYCfqQVwQvcteTY4S/NYV1Xj+fQBfO6EgHZ5k8FPd2DoJymivzkcnewhREgWkXwGidru13yJ4eaCl6v7eHo2wupTNXX3ug2/j/l9lV9yXBdAF72FcskdiSdJF2XvaNTI/u9Jz8QJnP9qrWm9TIheaJJgsToNSI9Qck1nnJ4Mq/59hnCADoYfx3OVoHwunCqgWC4VmoYpuV21FH7B1nkEs1mvbxADVIgyt3Q2MBwHHsittVFjBRuZhJHGEo0KP8spnm+7XmD3GiF2K+fzge8YXn5fDCCxqbUr9Bs2YEzac8JRx60FQAboZez4bcbbkOkfiKkSPNBuCmDr,iv:N88VZroKpgHLozt45+dTS8QNJRGoqT6KB5f6ZQeRwIQ=,tag:35w2oGtW1i++9hvXQMjLKg==,type:str]
sops:
    age:
        - recipient: age1exre38frn2yaqqgjmdp39uqs2uc97r8p52nhhytt8g9tks0tdyvs37s7sq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMnRIOVBJMWZmckt3MnFx
            M3NUUTRrVWRqMjNGc2wrWjJ1MkJhaXJhN1dvCktjUVhXMTN0c3hMT1ZPa0RwMGNW
            K0VSU3A2YTVOdWlkYVphYWJCeFRRYncKLS0tIGEySzM0RFpVU0pNZHNZT3ltVHg3
            QVlsQ0F2RWtPQ0tSc0lyVWpoTjFLUUkKe1ptBIsGKiJeOuh3GhUuaZ+798mRklVd
            HMXFmbm+mi40wO2B8/i5tjIk4hKGpgVrXNMc6EqfAIuK99yjbkXdcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T15:03:06Z"
    mac: ENC[AES256_GCM,data:k6z+p+k6pha6tfvLj2nWto1tDfqjnKYU9cIsTBNPN6YCprKwWcoC4ZhjV8DDlmKZ+ipCMmKSWD1R7d+npNoWCd8c/4cVZQeHYsxd/urAEeZMz9Ai1mUgOK54X4Ga9UKYES3bCZTDtCvdiRcAGObDbOoyeCLoDvqJ3n6cs9mL0h0=,iv:6aKQsF5X6gguRRibOl3+vJH9G3yKoezUpXAUfys+lr8=,tag:ZcMNnKp6udYT67zunBrPWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
