apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/alterac
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
