apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
type: Opaque
stringData:
    webserver_api_password: ENC[AES256_GCM,data:0k1XhWAsxhGIhzcTCFS4EfPSSQ==,iv:rtuABxAoKsIp/3coDNOST/YVqem8+68g2XK5aO3aWXY=,tag:eogSy8c4ViTrW0ZKZki2ug==,type:str]
sops:
    age:
        - recipient: age1exre38frn2yaqqgjmdp39uqs2uc97r8p52nhhytt8g9tks0tdyvs37s7sq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bW5pQTcxSWFvTnNRQkFI
            Y0YwOHo5R3VWODg3YWxEZU9zSDBYR1dwZDF3CmhSWG04dmVTbFlaOEx2WWNUWitR
            NkpYOEh0Qi80S2Z4b1hib2JEYnJjVWsKLS0tIFVlaXdPWlZ4YUZaT0F3RTJDNnlm
            dzV3UURVVFA5a3JNci9wQWhzdzltcEEKJmXxuzXZG6H9zuig6p2x1S+AJu2c6y9p
            1MidHo/dpViKSxOKU2Qz9bI7w16rF6dMpv1H4BVLsJt5BFPtQ/Tr4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T17:31:41Z"
    mac: ENC[AES256_GCM,data:Ly56pd1pdSoTwEo6b2y69tSAm9VPlq+ES2DrDwjLNFhQs9wWSPXh+M2u8oKQET3D/KZFzQ+swVCEtfw5QKBEyXgrmIv1EaJFnC6wsj+EWMi8TGZ43yGLPNG6/qoglDsK4+lsFLoHwDJ743saY9kxu7DnPc8y198pRrR4WM5m0I8=,iv:GsgDLFClG12zjXoDBzHLQWvYgV/qUhsU5fQPJ2eIWRc=,tag:DEipl3LAuD9n2Z4EZGeXWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
