apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-storage
  namespace: pihole
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 512Mi