apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  chart:
    spec:
      chart: cilium
      version: v1.18.x
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 1h
  values:
    encryption:
      nodeEncryption: true
      type: wireguard

