apiVersion: v1
kind: Secret
metadata:
    name: truenas-nfs-driver-config
    namespace: storage
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:VKmXbyF069zDFZNPA6dK5ADksgb2nlvtDnEVR5JVsyfHSyOpfbi2MD41SMQcTSGIgxOJ4dGi/uD2bbLMELQI7I1LqFOH6AbutPZGxnsDtR8Tjlc1tF4QeTWnAdFY5c7X6fH5Vq0RK34BYCAG1mGtQb1gl8OboTSdIKO3RyyhFLTm3VUGQoXA4csRWqfXuFWT6vtRe8XPPlPR3hQPZfssXv4u872pv4CS7zXwSBrJBvoMoo5AdAPj4IEJozAZ8DEYLIjEweOxwWyZ/I46RvHcobfedZj68R4KzlwGDTswF/F4aojl9GwWe1aZTWYznT+Rbx0/DMebfqRojWg1KLyI5x8uyrh0nLgZgy0F2eRbmuuZowqoRNAh2kZe7nQNdsg+CRd/qcIFq9AHqkfpdl3LsXMZqT0K9K7+nGnGdlGuFxMZfD/KlRs6NGIQJIdEX7fN13Kav35MHXHNVLIWYZVaowJBH5sbWqM8oD0p9MUpO9K+HJRsgXC6Uutv7LrsjKd+bWS9Z22eOte+s+P51+mJe21Y5gK7Al+Ye7eAbSiu26IY1clYGY+LSGbT1532zOu7MPH6JHKdD3qS6o/NAk/0yQD460gRmR2JmxJahtmp51l2mx0yr4WUYcxmb+zdR/GQmT3Ne4PjJtbUMnz0I5XZKO7FdBGF7SFtZUI/tMIRUxwO5pFDh4sn+olD21xGkiSfO2efswHNCJayqC4036WLLsN6ZTPIfcfLpUBZGbXhWGxMHFGghPyT9jCrxA8wVIOcxyghylX0iM8YsnBQY84xV3a7qt31QlbrnMx9atUaMfsKj6+IygqdO+M3Fc9SUAIOEv/X+c82eIJCjAxyL3Ck+4NTOyjxTmagV5LbDI7K7H6o2nKNrOauuyoB94IeVZTQ1ncahdzDNmrZNjO3ttltlD2pMFOPXWilADEG6Py2yQ6sEwDXDhNkWFRnOlfA8JHbuTYw0xZjzHDl3LxB1tqIS90UQcskbz+bu9fRKQU4XKKAu4Q0Tcv+DqndCrbRh5wTjOPlYZypE0Ni1u6SpE1QhhfAfS3dP8xs3Rnb5yZGwsL0iEbltINX6Hy0FaHP1Uztfmu5hlc+zayRcDiISILBDhxBDMpswKsxWfIQ9neAnA3vn9wEyOiwkGQYAV6cS6WBHJydFlMg1ZG7Exx5TkbVbY497/RfYN9gHAa3Bm/FBDQNo5EFDnJ3BZZG,iv:n6Ooe0/lxWFNAjNmCjJTNzoGPLDXDeC5lEMP+fRulek=,tag:b8Ayx+hy2SQwAjymI5dW4w==,type:str]
sops:
    age:
        - recipient: age1exre38frn2yaqqgjmdp39uqs2uc97r8p52nhhytt8g9tks0tdyvs37s7sq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOU5rbVlzbGpuaDFWRDk1
            NTBmUXlPVTNuaTh6dG80WTF4NE11MTJyWmlrClUrQW85UGNid1VjY09adnJSbTFs
            ZTZDRFVmZEpXOWxVdlNRK1dBejJQeFkKLS0tIDkzY3d5Vm8xSTltMUNnaDdmQ3Bh
            NXBSUTM3Sng1VnRiUW53US90Zk1FV0kKEiOuuNKvLIBeUKPYTPKKJaFrhNT8kSsB
            kbG12TdqhxWK4m2+4Wf3TzLtsblNIFUgUsFigQUFlDOjBUbp8Orihw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T16:53:05Z"
    mac: ENC[AES256_GCM,data:dw7NiV9ouSqJkqYlCjtIWnc9ieowzz8I3ytBV+A1TZWtPn+3hO8//d0+20UYo/sqKunHGlDq8NYwlL1Rbhd/HMwztkZcDyR+lnks0sF1+euArc0bjzj2pL4i4XQ1ewH/ezwYneQLyqc/DJ5G68a8WQiY2qfucmv6H447RMa0txw=,iv:xWALGq6PVu5kTt1J4aqdzqLSo1HhcYXb0C2p16v6wmo=,tag:GVppGIPP/ylNB6vsTV82Sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
