apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.x
      interval: 5h # this is for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: nginx
  releaseName: nginx
  targetNamespace: nginx
  interval: 1h # this is for drifting of the helm created resources
  values:
    controller:
      service:
        type: ClusterIP
      metrics:
        enabled: true
        serviceMonitor:
          additionalLabels:
            release: prometheus
          enabled: true
