apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 10m
  values:
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        additionalScrapeConfigs:
          - job_name: 'snmp'
            static_configs:
              - targets: ['192.168.1.1']
            metrics_path: /snmp
            params:
              module: [if_mib]
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: prometheus-snmp-exporter.monitoring.svc.cluster.local:9116
            scrape_interval: 30s
