kind: Secret
apiVersion: v1
metadata:
    name: kube-prometheus-stack-grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:gC7NTftYk324uuPaA/9c3j+OUHMbPUSHKHnmT99zi4hOCErrhFlD75eRQHyYNmlvi7QwtBb76g==,iv:yuio2WjpWZnhwx0gy61YLFcHIqp5Axa8EMuHg7uLWK4=,tag:UHXwgFmq3Mqfw1565rSY6w==,type:str]
sops:
    age:
        - recipient: age1exre38frn2yaqqgjmdp39uqs2uc97r8p52nhhytt8g9tks0tdyvs37s7sq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFhvVUNMc2VwR2xuOEg3
            MmQxUnVyV24wSVBRRkZaZVdGNmdvRys1QVM4CjkyWHAxMGRtNGkzS3NkMXBSMlo4
            c3JnY2Y5SlQvd3dWWUM2c2RJK3VJU0kKLS0tIEZPcDlXMVhJSFQwenU4aWgrY0xq
            QmJPNjNoVXRieXprY0hUY293dmN2NHMKn0PZPnfi5pHpHS280IhI8rmZJja0H01Q
            lnu1HfOSI/m+3lRiMglw+koj/nH4+tDe1Svm2nXYD3UEToEbSHIT+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T05:49:59Z"
    mac: ENC[AES256_GCM,data:2L+zpAlSdD1m1bhVROLNDorvcySBa7UV1/P5SUeNNiRXMbLdLdv8suBhaZGuPccBdpVtlqqRxMhGSH5KvO/9iSuP3++l0LfYZZGWZ/Hh5Dx0hc5L37jQNx3UEn3Y5uuxK0JCwLyQ1khUJ+EwHDMKsRldMoA/GCiS33fJwdq9jrY=,iv:Zt1xwCUjIsbnI9i2NYiUnPgsYKfV4PFZAC60KT6hht0=,tag:dzRcy0tYpw3osha/WZqPlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
