apiVersion: v1
kind: Service
metadata:
  name: linkding-service
  namespace: linkding
spec:
  selector:
    app: linkding-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
---

