apiVersion: v1
kind: Service
metadata:
  name: linkding-service
  namespace: linkding
spec:
  selector:
    matchLabels:
      app: linkding
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
